version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - db
    # volumes:
    #   - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql


      
networks:
  db:

    